export default {
  'data': [
    {
      'class': 'com.doublechaintech.cmes.parentmerchant.ParentMerchant',
      'displayName': '广钢集团有限公司0001',
      'messageList': [],
      '@objId': 'PM000001',
      'name': '广钢集团有限公司0001',
      'merchant': {
        'class': 'com.doublechaintech.cmes.merchant.Merchant',
        'displayName': '广钢集团',
        'messageList': [],
        '@objId': 'M000001',
        'name': '广钢集团',
        'code': 'xxxx0001',
        'fastKey': 'xxx0001',
        'address': '天府三街0001',
        'contactName': '张三？0001',
        'contactMobile': '189****0001',
        'contactEmail': 'email@company.com',
        'createTime': 1636400902000,
        'lastUpdateTime': 1636511839000,
        'merchantStatus': {
          'class': 'com.doublechaintech.cmes.merchantstatus.MerchantStatus',
          'displayName': '营业中',
          'messageList': [],
          '@objId': 'OPERATION',
          'name': '营业中',
          'code': 'OPERATION',
          'version': 1,
        },
        'merchantType': {
          'class': 'com.doublechaintech.cmes.merchanttype.MerchantType',
          'displayName': '充装单位',
          'messageList': [],
          '@objId': 'FILL_FACTORY',
          'name': '充装单位',
          'code': 'FILL_FACTORY',
          'category': 'default',
          'version': 1,
        },
        'owner': {
          'class': 'com.doublechaintech.cmes.naturalperson.NaturalPerson',
          'displayName': '李军勇',
          'messageList': [],
          '@objId': 'NP000001',
          'name': '李军勇',
          'mobile': '180****1234',
          'createTime': 1635644964000,
          'version': 1,
        },
        'platform': {
          'class': 'com.doublechaintech.cmes.platform.Platform',
          'displayName': '气瓶制造执行系统0001',
          'messageList': [],
          '@objId': 'P000001',
          'name': '气瓶制造执行系统0001',
          'createTime': 1634742253000,
          'lastUpdateTime': 1634743164000,
          'version': 1,
        },
        'version': 1,
        'parentMerchantList': [
          {
            'class': 'com.doublechaintech.cmes.parentmerchant.ParentMerchant',
            'displayName': '广钢集团有限公司0001',
            '@ref': 'PM000001',
            'version': 1,
          },
          {
            'class': 'com.doublechaintech.cmes.parentmerchant.ParentMerchant',
            'displayName': '广钢集团有限公司0002',
            'messageList': [],
            '@objId': 'PM000002',
            'name': '广钢集团有限公司0002',
            'merchant': {
              'class': 'com.doublechaintech.cmes.merchant.Merchant',
              'displayName': '广钢集团',
              '@objId': 'M000001',
              'version': 1,
            },
            'objectId': 'M0000010002',
            'objectType': 'Merchant',
            'description': '应集团要求，把集团添加为本公司上级组织0002',
            'createTime': 1636293596000,
            'version': 1,
          },
        ],
        'parentMerchantListStatsInfo': null,
        'parentMerchantCount': 2,
        'parentMerchantCurrentPageNumber': 1,
      },
      'objectId': 'M0000010001',
      'objectType': 'Merchant',
      'description': '应集团要求，把集团添加为本公司上级组织0001',
      'createTime': 1635605388000,
      'version': 1,
    },
    {
      'class': 'com.doublechaintech.cmes.parentmerchant.ParentMerchant',
      'displayName': '广钢集团有限公司0002',
      '@ref': 'PM000002',
      'version': 1,
    },
  ],
};
